---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Force delete default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy EpicBook Config
  template:
    src: theepicbooks.conf.j2
    dest: /etc/nginx/sites-available/epicbook # Hardcoded name
  notify: restart nginx

- name: Create Symlink
  file:
    src: /etc/nginx/sites-available/epicbook
    dest: /etc/nginx/sites-enabled/epicbook # Hardcoded name
    state: link
  notify: restart nginx

- name: Ensure Nginx is Started
  service:
    name: nginx
    state: started
    enabled: yes