---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Force remove default configurations
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default

- name: Copy EpicBook config to sites-available
  template:
    src: theepicbooks.conf.j2
    dest: /etc/nginx/sites-available/epicbook
    mode: '0644'

- name: Enable EpicBook config via symlink
  file:
    src: /etc/nginx/sites-available/epicbook
    dest: /etc/nginx/sites-enabled/epicbook
    state: link

- name: Test Nginx syntax
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Restart Nginx to apply changes
  service:
    name: nginx
    state: restarted
    enabled: yes