trigger: none

resources:
  pipelines:
    - pipeline: infra
      source: infra-epicbook.git
      trigger: true
  repositories:
    - repository: external_assignment
      type: github
      name: pravinmishraaws/theepicbook
      endpoint: dowusubekoe-dev

variables:
  - group: epicbook-secrets
  - name: vmPublicIp
    value: '20.123.200.55'
  - name: db_host
    value: 'epicbook-mysql-lkjb4a.mysql.database.azure.com'


pool:
  name: 'epicbook-deploy-agent'

steps:
  - checkout: self
    displayName: 'Checkout Ansible Playbook'

  - download: infra
    artifact: infra-outputs
    displayName: 'Get Latest Infra Data'
    continueOnError: true

   # DOWNLOAD PRIVATE KEY FROM SECURE FILES
  - task: DownloadSecureFile@1
    name: sshKey
    inputs:
      secureFile: 'id_rsa'

  # RUN DEPLOYMENT
  - script: |
      chmod 600 $(sshKey.secureFilePath)
      export ANSIBLE_PRIVATE_KEY_FILE=$(sshKey.secureFilePath)

        ansible-playbook -i inventory.ini site.yml \
        --private-key="$(sshKey.secureFilePath)" \
        -e "ansible_host=$(vmPublicIp)" \
        -e "db_host=$(db_host)" \
        -e "db_user=$DB_USER" \
        -e "db_password=$DB_PASSWORD" \
        -u azureuser --become \
        -vvv
    displayName: 'Execute Role-Based Deployment'
    env:
      ANSIBLE_HOST_KEY_CHECKING: 'False'
      DB_PASSWORD: $(db_password)
      DB_USER: $(db_admin_user)@epicbook-mysql-lkjb4a


  # VERIFY
  - script: |
      echo "DB_USER=$DB_USER"
      echo "Password length = ${#DB_PASSWORD}"
    displayName: 'Debug Env Variables'
    env:
      DB_PASSWORD: $(db_password)
      DB_USER: $(db_admin_user)@epicbook-mysql-lkjb4a


  # VERIFY
  - script: |
      echo "Waiting for Nginx and PM2 to settle..."
      sleep 20
      echo "Testing connection to http://$(vmPublicIp)"
      curl -f -I http://$(vmPublicIp)
    displayName: 'Final Health Check'