trigger: none

resources:
  pipelines:
    - pipeline: infra
      source: infra-epicbook.git
      trigger: true
  repositories:
    - repository: external_assignment
      type: github
      name: pravinmishraaws/theepicbook
      endpoint: dowusubekoe-dev

variables:
  - group: epicbook-secrets
  - name: vmPublicIp
    value: '20.123.200.55'
  - name: db_host
    value: 'epicbook-mysql-lkjb4a.mysql.database.azure.com'


pool:
  name: 'epicbook-deploy-agent'

steps:
  - checkout: self
    displayName: 'Checkout Ansible Playbook'

  - download: infra
    artifact: infra-outputs
    displayName: 'Get Latest Infra Data'
    continueOnError: true

   # DOWNLOAD PRIVATE KEY FROM SECURE FILES
  - task: DownloadSecureFile@1
    name: sshKey
    inputs:
      secureFile: 'id_rsa'

  # RUN DEPLOYMENT
  - script: |
      chmod 600 $(sshKey.secureFilePath)
      export ANSIBLE_PRIVATE_KEY_FILE=$(sshKey.secureFilePath)

      ansible-playbook -i inventory.ini site.yml \
        --private-key="$(sshKey.secureFilePath)" \
        -e "ansible_host=$(vmPublicIp)" \
        -e "db_host=$(db_host)" \
        -u azureuser --become -vvv
    displayName: 'Execute Role-Based Deployment'
    env:
      ANSIBLE_HOST_KEY_CHECKING: 'False'
      DB_USER: $(db_admin_user)@epicbook-mysql-lkjb4a
      DB_PASSWORD: $(db_password)

  # VERIFY
  - script: |
      echo "DB_USER set: $(test -n "$DB_USER" && echo YES || echo NO)"
      echo "DB_PASSWORD length: ${#DB_PASSWORD}"
    displayName: 'Debug Env Variables (Safe)'
    env:
      DB_PASSWORD: $(db_password)
      DB_USER: $(db_admin_user)@epicbook-mysql-lkjb4a


  # VERIFY
  - script: |
      echo "Waiting for application to become healthy..."

      for i in {1..10}; do
        if curl -sf http://$(vmPublicIp) > /dev/null; then
          echo "App is up"
          exit 0
        fi
        echo "Not ready yet... retrying ($i)"
        sleep 5
      done

      echo "App failed to become healthy"
      exit 1
    displayName: 'Final Health Check'