[web]
epicbook_server ansible_host={{ vm_public_ip }}

[web:vars]
ansible_user=azureuser
ansible_connection=ssh
# This allows Ansible to bypass the "Are you sure you want to connect" prompt automatically
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
# Ensures Ansible uses the correct Python version on Ubuntu 24.04
ansible_python_interpreter=/usr/bin/python3
# Essential for 'become' tasks on Azure to avoid permission errors
ansible_remote_tmp=/tmp/ansible-tmp