[web]
20.43.19.106

[web:vars]
ansible_user=azureuser
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
ansible_remote_tmp=/tmp/ansible-tmp