---
- name: restart epicbook
  command: pm2 restart epicbook --update-env
  args:
    chdir: "{{ app_dest }}"
  become: true
  become_user: "{{ app_user }}"
  environment:
    PM2_HOME: "{{ pm2_home }}"

- name: restart mysql
  service:
    name: mysql
    state: restarted