- name: Start App with PM2
  shell: |
    pm2 delete epicbook || true
    PORT={{ app_port }} pm2 start server.js --name "epicbook"
  args:
    chdir: "{{ app_dest }}"
  become_user: "{{ app_user }}"
  environment:
    PM2_HOME: "{{ pm2_home }}"