---
app_repo: "https://github.com/dowusubekoe-dev/theepicbook-praveen.git"
app_dest: "/var/www/epicbook"
app_user: "www-data"
app_group: "www-data"
nginx_site_name: "epicbook"
app_port: 3000
db_user: "dbadmin"
db_name: "bookstore"
db_host: "dmi-ch2-epicbook-prod-mysql-7sl5ny.mysql.database.azure.com"
db_password: "BenefitWallet2026!"
pm2_home: "/var/www/.pm2"