name: Sync to Azure Repo
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Azure DevOps
        run: |
          # Use the secret you just created for authentication
          git remote add azure https://${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/derekobekoe/epicbook-dual-pipeline/_git/infra-epicbook
          git push azure main --force